export const TRENDING_MOVIES_REQUEST = 'TRENDING_MOVIES_REQUEST';
export const TRENDING_MOVIES_SUCCESS = 'TRENDING_MOVIES_SUCCESS';
export const TRENDING_MOVIES_FAIL = 'TRENDING_MOVIES_FAIL';

export const TRENDING_TVS_REQUEST = 'TRENDING_TVS_REQUEST';
export const TRENDING_TVS_SUCCESS = 'TRENDING_TVS_SUCCESS';
export const TRENDING_TVS_FAIL = 'TRENDING_TVS_FAIL';