export const TRENDING_MOVIES_REQUEST = 'TRENDING_MOVIES_REQUEST';
export const TRENDING_MOVIES_SUCCESS = 'TRENDING_MOVIES_SUCCESS';
export const TRENDING_MOVIES_FAIL = 'TRENDING_MOVIES_FAIL';

export const TRENDING_TVS_REQUEST = 'TRENDING_TVS_REQUEST';
export const TRENDING_TVS_SUCCESS = 'TRENDING_TVS_SUCCESS';
export const TRENDING_TVS_FAIL = 'TRENDING_TVS_FAIL';

export const MOVIE_GENRES_REQUEST = 'MOVIE_GENRES_REQUEST';
export const MOVIE_GENRES_SUCCESS = 'MOVIE_GENRES_SUCCESS';
export const MOVIE_GENRES_FAIL = 'MOVIE_GENRES_FAIL';

export const TVSHOW_SEASONS_REQUEST = 'TVSHOW_SEASONS_REQUEST';
export const TVSHOW_SEASONS_SUCCESS = 'TVSHOW_SEASONS_SUCCESS';
export const TVSHOW_SEASONS_FAIL = 'TVSHOW_SEASONS_FAIL';

export const DETAILS_REQUEST = 'DETAILS_REQUEST';
export const DETAILS_SUCCESS = 'DETAILS_SUCCESS';
export const DETAILS_FAIL = 'DETAILS_FAIL';