export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_FAIL = 'SEARCH_MOVIE_FAIL';

export const SEARCH_TV_REQUEST = 'SEARCH_TV_REQUEST';
export const SEARCH_TV_SUCCESS = 'SEARCH_TV_SUCCESS';
export const SEARCH_TV_FAIL = 'SEARCH_TV_FAIL';