export const WATCHLIST_ADD_SUCCESS = 'WATCHLIST_ADD_SUCCESS';
export const WATCHLIST_ADD_FAIL = 'WATCHLIST_ADD_FAIL';

export const WATCHLIST_REMOVE_SUCCESS = 'WATCHLIST_REMOVE_SUCCESS';
export const WATCHLIST_REMOVE_FAIL = 'WATCHLIST_REMOVE_FAIL';